config/routes.rb
Rails.application.routes.draw do
  # resources :favorites
  resources :complaints
  resource :session, only: [:new, :create, :destroy] #note singular form "resource and session. SINGULAR session"
  root "users#index"
  resources :brands

  get "login" => "sessions#new"
  get "signup" => "users#new"
  get "/users/:user_id/items/filter/:filter" => "items#index", as: :filtered_items


  resources :users do
    resources :items do
      resources :favorites, only: [:create, :destroy] #three layer nesting
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # audited 
  audited 
  # (looks like password digest already handles this sensitive info! The above line is redundant.)
  has_many :items, dependent: :destroy #destroy all items when a user is destroyed.
  has_many :favorites, dependent: :destroy # if a user is destroyed, all of its favorites are also destroyed.
  has_many :favorite_items, through: :favorites, source: :item
  accepts_nested_attributes_for :items
  # the has secure password is automatically generated when you create a resource with a "password:digest" field
  has_secure_password 

validates :name, presence: true #, uniqueness: { case_sensitive: false }
validates :email, presence: true,
  format: { with: /\S+@\S+/ },
  uniqueness: { case_sensitive: false }
# validating the password length if it is not blank (validation will be skipped if it is blank)
validates :password, length: { minimum: 10, allow_blank: true }

validates :username, allow_blank: true,
                     format: { with: /\A[A-Z0-9]+\z/i },
                     uniqueness: { case_sensitive: false }

def gravatar_id
  Digest::MD5::hexdigest(email.downcase)
end

scope :everyone, -> { all.order(:name) }


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :index, :show, :create]
  before_action :edit_correct_account, only: [:edit, :update, :destroy]

    def index
        # @users = User.everyone 
        #safe commit!
        @users  = User.everyone.paginate(:page => params[:page], :per_page=>10)
    end

    def show # USER SHOWPAGE
        # @user = User.find(params[:id])
        @user = User.find(params[:id])
        @favorite_items = @user.favorite_items.paginate(:page => params[:page], :per_page=>3)
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id #automatically signing in the user when they create an account.
          redirect_to @user, notice: "Thanks for signing up!"
        else
          render :new
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        # @user = User.find(params[:id])
        if @user.update(user_params)
          redirect_to @user, notice: "Account successfully updated!"
        else
          render :edit
        end
      end

      def destroy
        # @user = User.find(params[:id])
        if current_user.admin? && current_user?(@user)
          @user.destroy
          session[:user_id] = nil 
          redirect_to login_url, alert: "Your account was successfully deleted!"  #this way no errors occur  
        elsif current_user.admin?
        @user.destroy
        redirect_to root_url, alert: "This user's account was successfully deleted!" 
        else
        @user.destroy
        session[:user_id] = nil
        redirect_to login_url, alert: "Your account was successfully deleted!"  #this way no errors occur  
        end
      end

      private
      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :username)
      end


      # moved to applications controller to be re-used efficiently for/on ITEMS
      # def require_correct_user
      #   @user = User.find(params[:id]) #removes duplication for edit update destroy actions!
      #   redirect_to root_url unless current_user?(@user)
      # end

end

app/helpers/users_helper.rb
module UsersHelper
    def profile_image(user)
        url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
        image_tag(url, alt: user.name, width: 75, height: 75)
      end
end

app/views/users/_displayusers.html.erb
<% if users_any? %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <% if current_user?(user) %>      
      View <%= link_to "your closet", user_items_url(user) %>
      <% else %>
      View <%= link_to "#{user.name.possessive} closet", user_items_url(user) %>
      <% end %>
    </li>
  <% end %>
<%= will_paginate @users %>  
<li><strong>View list of brands <%= link_to "here", brands_url, class: "button" %></strong></li>
</ul>

<% else %>
<h3>No users yet.</h3>
<p> Be the first to join <%= link_to("here", signup_url) %>! </p>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <%= render "shared/errors", object: user %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label "username (optional)" %>
  <%= f.text_field :username, placeholder: "Alphanumeric characters only!" %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>

  <% if user.new_record? %>
  <%= f.submit "Create Account" %>
      <p></p> 
      <p>Already have an account? <%= link_to("Log In!", new_session_path)%></p>
  <% else %>
  <%= f.submit "Update Account" %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Account Settings</h1>
<%= render "form", user: @user %>

<% if admin_or_current_user %>
<section class="user">
  <div class="actions">
     &emsp;<%= link_to "Delete Account", @user, method: :delete, 
        data: { confirm: "Permanently delete account?! \nThis cannot be undone." },
        class: "button delete" %>
  </div>
  </section>
 <% end %>

app/views/users/index.html.erb
<h1 class="user-index-header">Welcome to Almost Plato's! </h1>
<%= render "displayusers", users: @users %>  

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render "form", user: @user %>

app/views/users/show.html.erb
<section class="user">
    <div class="details">
     <%# ^^ FOR USER DETAILS %>
  <%= profile_image(@user) %>
  <p></p>
  <h1><%= @user.name %> 
    <% if @user.username.present? %>
    (<%= @user.username %>)
    <% end %>
  </h1>
  <h2><%= mail_to(@user.email) %></h2>
  <p>
    <% if current_user?(@user) %>
       View your items <%= link_to "here", user_items_url(@user) %> 
    <% else %>
       View <%= (@user.name.possessive) %> items <%= link_to "here", user_items_url(@user) %> 
    <% end %>
  </p>
   <p> Member since
    <%= @user.created_at.strftime("%B %Y") %>
  </p>
  
  <% if current_user && current_user.admin? && current_user?(@user)%>
  <p><b>You are an admin user.</b></p>
  <p>You may edit and delete users' items and accounts.</p>
  <% elsif @user.admin? %>
    <p><b><%= @user.name %> is an admin user.</b></p>
  <% end %>

<% if admin_or_current_user %>
  <div class="actions">
        <%= link_to "Edit Account", edit_user_path(@user),
        class: "button edit" %>

        <%= link_to "Delete Account", @user, method: :delete, 
        data: { confirm: "Permanently delete account?! \nThis cannot be undone." },
        class: "button delete" %>
  </div>
 <% end %> 
 </div> 
 <%# ^^ FOR USER DETAILS %>
 <aside>
 <% if @favorite_items.present? %>
 <br>
  <h4>Liked Items </h4>  
  <div class="favorite-movies">
    <% @favorite_items.each do |item| %>
    <% @new_user = item.user_id %>
      <%= link_to main_image(item), user_item_url(@new_user, item) %>   
    <% end %>
  </div>
<% end %>
<%= will_paginate @favorite_items, renderer: WillPaginate::ActionView::BootstrapLinkRenderer  %>
</aside>
</section>