config/routes.rb
Rails.application.routes.draw do
  # resources :favorites
  resources :complaints
  resource :session, only: [:new, :create, :destroy] #note singular form "resource and session. SINGULAR session"
  root "users#index"
  resources :brands

  get "login" => "sessions#new"
  get "signup" => "users#new"
  get "/users/:user_id/items/filter/:filter" => "items#index", as: :filtered_items


  resources :users do
    resources :items do
      resources :favorites, only: [:create, :destroy] #three layer nesting
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  # uses singular form of the parent (user) for one to many
  # no dependent destroy in this direction. Destroying item does NOT destroy user.
  belongs_to :user 
  audited associated_with: :user #audit setup
  # Now, when an audit is created for a item, that item's user is also saved alongside the audit. 
  # This makes it much easier (and faster) to access audits indirectly related to a user.
has_one_attached :main_image
has_many :characterizations, dependent: :destroy
has_many :complaints, through: :characterizations
has_many :favorites, dependent: :destroy
# ^ if an item is destroyed, all of its favorites are also automatically destroyed.
has_many :fans, through: :favorites, source: :user

    FLAIRS = ["no flair", "Bought", "Sold", "User Favorite"]

    SIZES = ["XS", "S", "M", "L", "XL", "Unknown", "One Size", "Other", "Shoe: 7.5M", "Shoe 8M", "Shoe 8.5W", "Shoe 9W", "Shoe 9.5W"]

    STARS = [1, 2, 3, 4, 5]

    BRANDS = Brand.all.pluck(:name)

  validates :description, :found_on, :stars, :size, :brand, presence: true
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  #^^ item names MUST be unique regardless of whether they use upper or lower case characters!
  validates :description, length: { minimum: 10 }
  validate :acceptable_image
  # ^^ private method defined further below 
  validates :flair, inclusion: { in: FLAIRS }
  validates :size, inclusion: { in: SIZES }
  # validates :brand, inclusion: { in: BRANDS } #THIS WORKS!
  validates :stars, inclusion: { in: STARS } 

# FOR ITEM MODEL
#shows ALL ITEMS by the most recently updated!
scope :all_items, -> { all.order("updated_at desc").order("found_on desc") } 
#shows RECENTLY ADDED with limit of 5 displayed
scope :recently_added, -> { all.order("created_at desc") } 
# scope :MOST LIKED, TO BE DEFINED LATER
#sorts all items by HIGHEST RATED, showing newest found_on at the top
scope :top_rated, -> { all.order("stars desc").order("found_on desc") }  
scope :flair_bought, -> { all.where(flair: "Bought") }  
scope :flair_sold, -> { all.where(flair: "Sold") }  
scope :flair_favorites, -> { all.where(flair: "User Favorite") }  


    def stars_as_percent
      (stars / 5.0) * 100.0
    end

    def self.bought
      where(flair: "Bought").order("found_on desc") #orders most recently found to the top!
    end

    def self.sold
      where(flair: "Sold").order("found_on desc") #orders most recently found to the top!
    end

    def self.favorite
      where(flair: "Favorite").order("found_on desc") #orders most recently found to the top!
    end

    private
    def acceptable_image
      return unless main_image.attached?
    
      unless main_image.blob.byte_size <= 3.megabytes
        errors.add(:main_image, "is too big (over 3MB)")
      end
    
      acceptable_types = ["image/jpeg", "image/png"]
      unless acceptable_types.include?(main_image.content_type)
        errors.add(:main_image, "must be a JPEG or PNG")
      end
    end


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
 
    before_action :require_login, except: [:new, :create, :index] #copied to items controller from users 
    before_action :edit_correct_item, only: [:edit, :update, :destroy] #copied to items controller from users
    before_action :add_new_correct_item, only: [:new] 
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index   
        @user = User.find(params[:user_id])  
        @container = @user.items.paginate(:page => params[:page], :per_page=>5)

       case params[:filter]
         when "all_items"
           @items = @container.all_items
         when "recently_added"
           @items = @container.recently_added
         when "top_rated"
           @items = @container.all.top_rated
        when "flair_bought"
            @items = @container.all.flair_bought
        when "flair_sold"
            @items = @container.all.flair_sold
        when "flair_favorites"
            @items = @container.all.flair_favorites
         else
            @items = @container.all_items #most recently updated are at the top
         end
       end

    def show
        @complaints = @item.complaints.order(:name)
        @fans = @item.fans
        if current_user
          @favorite = current_user.favorites.find_by(item_id: @item.id)
        end
    end

    def edit
        @complaints = @item.complaints.order(:name)
    end

    def update
        if @item.update(item_params)
        redirect_to user_item_url(@user, @item), notice: "Item successfully updated!"
        else
         render :edit
      end
    end

    def new
        @user = User.find(params[:user_id])
        @item = @user.items.new
    end

    # def create
    #     @item = Item.new(item_params)
    #    if  @item.save
    #     redirect_to @item, notice: "Item successfully created!"
    #    else
    #     render :new
    #    end
    # end

    def create
        @user = User.find(params[:user_id])
        @item = @user.items.new(item_params)  
        if @item.save && current_user = @user
            redirect_to user_items_path(@user),
                          notice: "Item successfully added!"
          else
            render :new, alert: "Cannot alter another person's items!" 
          end
        end      

    def destroy
        @item.destroy
        redirect_to user_items_path(@user), alert: "Item successfully deleted!"
    end

    private
    def item_params
        params.require(:item)
        .permit(:name, :stars, :description, :found_on, :brand, :size, :flair, :main_image, complaint_ids: [])
    end

    def set_user
        @user = User.find(params[:user_id])
        @item = @user.items.find(params[:id]) # I DID IT

        # @item = Item.find(params[:user_id])
       
        # if @item.nil? && current_user
        #     redirect_to user_path(@current_user), alert: "unauthorized access!"
        # elsif @item.nil? 
        #     redirect_back(fallback_location: login_path, alert: "unauthorized access!")
        # else
        #     @item = Item.find(params[:user_id])
        # end
    end

end

app/helpers/items_helper.rb
module ItemsHelper
    def format_found_on(item)
        # MAKE METHODS NIL SAFE (this will only run if the found_on attribute is not nil)
        if item.found_on.present? 
            # only runs if date is in a valid format (Date class) for ^^^ strftime!
            item.found_on.strftime("%-m.%-d.%-y")
            # %D is the same as %m/%d/%y 
        end
    end

    def format_updated_at(item)
        #Already nil safe because "updated at" always exists for objects.
        #(currently inactive, replaced with another helper method inside the view template)
        item.updated_at.strftime("%B %e at %I:%M %p") 
    end

    def nav_link_to(text, url)
        if current_page?(url)
          link_to(text, url, class: "active")
        else
          link_to(text, url)
        end
      end

      def main_image(item)
        if item.main_image.attached?
          image_tag item.main_image
        else
          image_tag "placeholder-2.png"
        end
      end

end

app/views/items/_form.html.erb
<%= form_with(model: [@user, @item], local: true) do |f| %>
<%= render "shared/errors", object: @item %>

  <%= f.label :item_name %>
  <%= f.text_field :name, autofocus: true %>

 <%= f.label :stars %>
  <% Item::STARS.each do |star| %>
    <span class="star">
        <%= f.radio_button :stars, star %>
        <%= label_tag star %>
    </span>
  <% end %>
  <p></p> 
<%# ^ adding some space after stars%>
  <%= f.label :optional_flair %>
  <%= f.select :flair, Item::FLAIRS, default: "no flair" %>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 5 %>

  <%= f.label :size %>
  <%= f.select :size, Item::SIZES, prompt: "Pick one" %>

  <%= f.label :brand %>
  <%= f.select :brand, Brand.all.pluck(:name).sort, prompt: "Pick one" %>

  <%= f.label :found_on %>
  <% if item.new_record? %>
  <%= f.date_field :found_on, :value => Time.now.strftime("%Y-%m-%d") %>
  <% else %>
  <%= f.date_field :found_on %>
  <% end %>

  <%= f.label :main_image %>
  <%= f.file_field :main_image %>

  <%= f.label "Complaints (optional)" %>
  <div class="checkboxes">
  <%= f.collection_check_boxes(:complaint_ids, Complaint.order(:name), :id, :name) %>
  </div>

  <%= f.submit %>
<% end %>

app/views/items/_h1flair.html.erb
<h1>
<% if item.flair == "User Favorite" %> 
     <%= "#{item.name}" %> &nbsp; <%= link_to "#{item.flair}", filtered_items_url(@user, :flair_favorites), class: "button-flair" %>
      <% elsif item.flair == "Bought" %>
      <%= "#{item.name}" %> &nbsp; <%= link_to "#{item.flair}", filtered_items_url(@user, :flair_bought), class: "button-flair" %>
       <% elsif item.flair == "Sold" %>
      <%= "#{item.name}" %> &nbsp; <%= link_to "#{item.flair}", filtered_items_url(@user, :flair_sold), class: "button-flair" %>
       <% elsif item.flair == "no flair" %>
      <%= item.name %>
      <% else %>
     Flair should not be nil
    <% end %>

<% if current_user != @user %> 
  <%# USERS CANNOT FAVORITE THEIR OWN ITEMS, ONLY OTHER USERS' ITEMS %>
  <div class="faves">
  <% if @favorite %>
     <%= button_to "♡ Unlike", user_item_favorite_path(@user, @item, @favorite), method: :delete %>
        <div class="count">
        <%= @fans.size %>
        </div>
    <% else %>
      <%= button_to "♥️ Like", user_item_favorites_path(@user, @item) %>
        <div class="count">
        <%= @fans.size %>
        </div>
    <% end %>
  </div>
<% end %>
</h1>
    

app/views/items/_indexpageheader.html.erb
<div class="index-page-header">
<% if current_user?(user) && items_any?(user) %>
   <h1><%= link_to(user.name.possessive, user_url(user)) %>&nbsp;closet (<%= user.items.size %>) <%= link_to "Add New Item", new_user_item_url(user), class: "button-add" %></h1>
   <% elsif current_user?(user) && items_any?(user) == false %>
      <h3>No items yet. <%= link_to "Add New Item", new_user_item_url(user), class: "button-add" %></h3>
   <% elsif current_user?(user) == false && items_any?(user) == false %>
      <h3>No items yet. </h3>
      <p> View <%= user.name.possessive %> account <%= link_to "here", user_url(user) %> </p>
   <% else %>
      <h1><%= link_to(user.name.possessive, user_url(user)) %> &nbsp;closet (<%= user.items.size %>)</h1> 
   <% end %>
</div>

   

app/views/items/edit.html.erb
<h1>Editing <%= link_to @item.name, user_item_path(@user, @item) %></h1>
<%= render "form", item: @item%>

app/views/items/index.html.erb
<%= render "indexpageheader", user: @user %>  
<div style="padding-left: 5o;padding-left: 50px;"><%= will_paginate @container %></div>

<% @items.each do |item| %>
<section class="movie">
  <div class="image">
    <%= link_to main_image(item), user_item_path(@user, item) %>
  </div>
  <div class="summary">
  <div class="header-2">
    <h2>
      <%= link_to(item.name, user_item_url(@user, item)) %>
        <% unless item.fans.size == 0 %>
        &nbsp;♥️ <%= item.fans.size %>
        <% end %>   
        <% unless item.flair == "no flair" || nil %>     
        <%#= link_to "#{item.flair}", user_item_url(@user, item), class: "button-flair-small" %>
        &nbsp; <button class="button-flair-small" ><%= item.flair %></button>
        <% end %>
    </h2>
  </div>
  <%= render "shared/stars", percent: item.stars_as_percent %>
      <% if item.found_on.present? %>
      <h3>Found <%= format_found_on(item) %></h3>
      <% end %>
      <p>
      <%= simple_format(item.description.truncate(75, separator: ' ')) %>
      </p>
  </div>
</section>
<% end %>
<div style="padding-left: 5o;padding-left: 50px;"><%= will_paginate @container %></div>

app/views/items/new.html.erb
<h1>New Item Listing</h1>
<%= render "form", item: @item%>

app/views/items/show.html.erb
<section class="movie-details">
<div class="image">
    <%= main_image(@item) %>
</div>

  <div class="details">
    <%= render "h1flair", item: @item %>    
    <h2>
        <%= render "shared/stars", percent: @item.stars_as_percent %>
      </h2>
      <p>
      <%= simple_format(@item.description) %>
        <%#= @item.description %> 
      </p>
      <table>
        <tr>
          <th>Size:</th>
          <td><%= @item.size %></td>
        </tr>
        <tr>
          <th>Brand:</th>
          <td><%= @item.brand %></td>
        </tr>
        <tr>
          <th>Found on:</th>
          <td><%= format_found_on(@item) %></td>
        </tr>
        <tr>
          <th>Last Updated:</th>
          <td><%= time_ago_in_words(@user.updated_at) %> ago </td>
        </tr>
         <tr>
          <th>Submitted By:</th>
          <td><%= link_to(@user.name, @user) %> </td>
        </tr>
      </table>

      <div class="complaints">
        <% if @complaints.present? %>
        <h4>Complaints:</h4>
        <ul>
        <% @complaints.each do |c| %>
        <li><%= c.name %></li>
        <% end %>
        </ul>
        <% end %>
      </div>
  </div>

<aside>
<% if @fans.present? %>
    <h4>Liked By</h4>
      <div>
          <ul>
              <% @fans.each do |user| %>
                  <%#= link_to profile_image(user), user %>
                  <ul>
                  <li>
                  <%= link_to user.name, user %>
                  </li>
                  </ul>
              <% end %>
          </ul>
      </div>
<% end %>
</aside>
</section>

<section class="admin">
  <% if admin_or_current_user %>
  <%#= link_to "Edit Item", edit_user_item_url(@user, item)), class: "button" %>
  <%= link_to "Edit Item", edit_user_item_path(@user, @item), class: "button" %>
  <%= link_to "Delete Item", [@user, @item], class: "button-delete", method: :delete,
  data: { confirm: 'Delete Item?!' }  %>
  <% end %>
</section>