config/routes.rb
Rails.application.routes.draw do
  # resources :favorites
  resources :complaints
  resource :session, only: [:new, :create, :destroy] #note singular form "resource and session. SINGULAR session"
  root "users#index"
  resources :brands

  get "login" => "sessions#new"
  get "signup" => "users#new"
  get "/users/:user_id/items/filter/:filter" => "items#index", as: :filtered_items


  resources :users do
    resources :items do
      resources :favorites, only: [:create, :destroy] #three layer nesting
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord
    validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
    before_action :require_login, only: [:index]
    before_action :admin_brand_access?, only: [:new, :create, :edit, :destroy]

    def index
        @brands = Brand.all.paginate(:page => params[:page], :per_page=>30)
    end

    def new
        @brand = Brand.new
    end

    def create
        @brand = Brand.new(brand_params) 
        if @brand.save
            redirect_to brands_url, notice: "Brand successfully added!"
        else
            render :new
        end
    end

    def edit
        @brand = Brand.find(params[:id])
        if @brand.name == "unknown" || @brand.name == "other"
        redirect_to brands_url, alert: "You may not alter the 'unknown' or 'other' brand."
        end
    end

    def update
        @brand = Brand.find(params[:id])
        @test = Item.where(brand: @brand.name)

        if @brand.update(brand_params)
            @test.each do |item|
                item.brand = "#{@brand.name}"
                item.save
            end
          redirect_to brands_url, notice: "#{@brand.name} successfully updated!"
        else
          render :edit
        end
      end

    def destroy
        @brand = Brand.find(params[:id])
        @test = Item.where(brand: @brand.name)
        
        if @brand.destroy
            @test.each do |item|
                item.brand = "unknown"
                item.save
            end
        redirect_to brands_url, alert: "Brand successfully deleted!"
        end
    end

    private
    def brand_params
        params.require(:brand)
        .permit(:name)
    end

end

app/helpers/brands_helper.rb
module BrandsHelper

    def item_size_for(brand)
        Item.where(brand: brand.name).size
        end

end

app/views/brands/edit.html.erb
  <%= form_with(model: @brand, local: true) do |f| %>
  <h1>Editing "<%= @brand.name %>"</h1>

  <%= render "shared/errors", object: @brand %>

  <%= f.label "Brand Name" %>
  <%= f.text_field :name, autofocus: true, required: true, placeholder: "(Rename?)" %>
  <%=f.submit "Update Brand", data: { confirm: "#{pluralize(item_size_for(@brand), "item")} will have their brand(s) updated." } %>

<section class="user">
  <div class="actions">
  &emsp;<%= link_to "Delete Brand", @brand, method: :delete, 
        data: { confirm: "Delete brand?! \n#{pluralize(item_size_for(@brand), "item")} will have their brand(s) set to 'unknown'." },
        class: "button delete" %>
  </div>
  </section>
<% end %>
<br>
<%= link_to("Back to all brands", brands_path) %>

app/views/brands/index.html.erb
<h1>All Brands (<%= Brand.all.size %>):</h1>
<% if current_user && current_user.admin? %>
<p>You have permission to modify this list.</p>
<% else %>
<p>Only admins can modify this list.</p>
<% end %>

<ul>
<div class="li-brands">
<% @brands.order("name asc").each do |brand| %>
<% if current_user && current_user.admin? %>
 <li><%= link_to brand.name, edit_brand_url(brand) %></li>
<% else %>
 <li><%= brand.name %></li>
<% end %>
<% end %>
</div>
</ul>
 <%= will_paginate @brands %>  

<section class="admin">
<% if current_user && current_user.admin? %>
<%= link_to "Add a Brand", new_brand_url, class: "button-add" %>
<% else %>
<% end %>
</section>

app/views/brands/new.html.erb
<h1>Add a new brand</h1>
  <%= form_with(model: @brand, local: true) do |f| %>
  <%= render "shared/errors", object: @brand %>

  <%= f.label "Brand Name" %>
  <%= f.text_field :name, autofocus: true, required: true, placeholder: "(No duplicates allowed!)" %>
  <%=f.submit "Add Brand"%>

<% end %>