config/routes.rb
Rails.application.routes.draw do
  # resources :favorites
  resources :complaints
  resource :session, only: [:new, :create, :destroy] #note singular form "resource and session. SINGULAR session"
  root "users#index"
  resources :brands

  get "login" => "sessions#new"
  get "signup" => "users#new"
  get "/users/:user_id/items/filter/:filter" => "items#index", as: :filtered_items


  resources :users do
    resources :items do
      resources :favorites, only: [:create, :destroy] #three layer nesting
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
<div class="container">
        <div>
                Some CSS Styles &copy; <%= Time.now.year %>
                <%= link_to 'Pragmatic Studio.','https://pragmaticstudio.com' %>
        </div>
        <div>
                <%= link_to image_tag("facebook-app.png", :height => 30), "https://www.facebook.com/American1diot/" %>
                &emsp;<%= link_to image_tag("ig-instagram.png", :height => 30), "https://www.instagram.com/heychickenhead/" %>
                &emsp;<%= link_to image_tag("linkedin-app.png", :height => 30), "https://www.linkedin.com/in/clark-jamie/" %>
                &emsp;<%= link_to image_tag("gh.png", :height => 30), "https://github.com/Elegant-Geek" %>
                &emsp;&emsp;&emsp; <%= link_to "Back to Top", '#', class: "button-anchor" %>
        </div>
</div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
        <%= link_to image_tag("final-logo.png", :height => 70), root_path %>
    <ul class="left">
    <% if current_user && @user %> 
    <%# displays a neat header with filters if a current user exists for the index/show pages %>
      <li>
          <%= nav_link_to "All Items", filtered_items_url(@user, :all_items) %>
      </li>
      <li>
          <%= nav_link_to 'Recently Added', filtered_items_url(@user, :recently_added) %>
      </li>
      <li>
          <%= nav_link_to 'Top Rated', filtered_items_url(@user, :top_rated) %>
      </li>
       <% end %>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li>
          <%= link_to current_user.name, current_user %>
        </li>
        <li>
            <%= link_to "Account Settings", edit_user_path(current_user) %>
        </li>
        <li>
       &ensp;<%= link_to "Log Out", session_path, method: :delete,
              class: "button" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign Up", signup_path, class: "button" %>
        </li>
        <li>
          &ensp;<%= link_to "Log In", login_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Almost Plato's</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <%= render "layouts/header" %>
    <%# this class="content" div makes the body spacing look really good %>
<div class="page-wrap">
    <div class="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
</div>
    <%= render "layouts/footer" %>
  </body>

</html>

 

   